---
- name: ensure nginx paths are set up
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - sites-available
    - sites-enabled
    - tmp/uwsgi
    - tmp/scgi
    - tmp/proxy
    - tmp/fastcgi
    - tmp/client_body

- name: ensure nginx cache paths are set up
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /tmp/nginx
    - /var/cache/nginx

- name: add www group
  group: name=www state=present

- name: add www user
  user: name=www group=www state=present

- name: copy nginx config template
  template: src=default dest=/etc/nginx/sites-available/default owner=root group=root mode=0644

- name: copy site nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default

- name: restart nginx
  service: name=nginx enabled=yes state=restarted
